"""Playwright-based cookie fetcher for video platforms.

Automatically launches a headless browser, visits the platform,
collects all cookies (including JavaScript-set ones), and saves
them in Netscape format for yt-dlp to use.
"""
import os
import tempfile
import logging
import asyncio
from typing import Optional

logger = logging.getLogger(__name__)

# 平台首页 URL（用于获取匿名 cookies）
PLATFORM_HOMEPAGES = {
    "bilibili_video": "https://www.bilibili.com/",
    "douyin_video": "https://www.douyin.com/",
    "xiaohongshu_video": "https://www.xiaohongshu.com/",
}


async def fetch_cookies_via_playwright(
    platform: str,
    video_url: Optional[str] = None,
    sessdata: Optional[str] = None,
) -> Optional[str]:
    """用 Playwright 无头浏览器获取平台 cookies

    Args:
        platform: bilibili_video / douyin_video / xiaohongshu_video
        video_url: 视频页面 URL（如果有，访问视频页获取更多 cookies）
        sessdata: B站 SESSDATA（如果有，注入到浏览器中）

    Returns:
        cookies.txt 文件路径，失败返回 None
    """
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        logger.error("Playwright 未安装，请运行: pip install playwright && playwright install chromium")
        return None

    homepage = PLATFORM_HOMEPAGES.get(platform)
    if not homepage:
        logger.error(f"不支持的平台: {platform}")
        return None

    # 访问目标 URL（视频页比首页能获取更多 cookies）
    target_url = video_url or homepage

    tmp_dir = tempfile.mkdtemp(prefix=f"kos_pw_{platform}_")
    cookie_file = os.path.join(tmp_dir, "cookies.txt")

    try:
        async with async_playwright() as p:
            # 启动无头浏览器：优先用系统已装的 Edge/Chrome（无需额外下载），兜底用 Playwright 自带 chromium
            browser = None
            for _channel in ("msedge", "chrome", None):
                try:
                    _kwargs = {"headless": True}
                    if _channel:
                        _kwargs["channel"] = _channel
                    browser = await p.chromium.launch(**_kwargs)
                    logger.info(f"浏览器启动成功 (channel={_channel or 'chromium'})")
                    break
                except Exception as e:
                    logger.warning(f"浏览器启动失败 (channel={_channel or 'chromium'}): {e}")
                    continue
            if not browser:
                raise RuntimeError(
                    "无法启动浏览器：请运行 'playwright install chromium' 或确保系统已装 Edge/Chrome"
                )

            context = await browser.new_context(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                           "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
                viewport={"width": 1920, "height": 1080},
            )

            # B站：注入 SESSDATA cookie
            if sessdata and platform == "bilibili_video":
                await context.add_cookies([{
                    "name": "SESSDATA",
                    "value": sessdata,
                    "domain": ".bilibili.com",
                    "path": "/",
                    "httpOnly": True,
                    "secure": True,
                    "sameSite": "Lax",
                }])
                logger.info("已注入 B站 SESSDATA cookie")

            page = await context.new_page()

            # 访问页面，等待网络空闲
            logger.info(f"Playwright 访问: {target_url}")
            try:
                await page.goto(target_url, wait_until="networkidle", timeout=30000)
            except Exception:
                # networkidle 超时也没关系，页面可能已经加载了
                logger.warning(f"页面加载超时，继续获取 cookies")

            # 等待一下让 JavaScript 设置 cookies
            await asyncio.sleep(2)

            # 收集所有 cookies
            cookies = await context.cookies()
            logger.info(f"Playwright 获取到 {len(cookies)} 个 cookies")

            if not cookies:
                logger.error("未获取到任何 cookies")
                await browser.close()
                return None

            # 写入 Netscape 格式 cookies.txt
            with open(cookie_file, "w", encoding="utf-8") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This is generated by KnowledgeOS Playwright cookie fetcher\n")
                for cookie in cookies:
                    domain = cookie.get("domain", "")
                    if not domain:
                        continue
                    # 确保 domain 以 . 开头（Netscape 格式要求）
                    if not domain.startswith("."):
                        domain = "." + domain.lstrip("www.")
                    path = cookie.get("path", "/")
                    secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                    expiry = int(cookie.get("expires", 0))
                    if expiry < 0:
                        expiry = 0
                    name = cookie.get("name", "")
                    value = cookie.get("value", "")
                    f.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

            await browser.close()

            logger.info(f"cookies.txt 已保存: {cookie_file} ({len(cookies)} cookies)")
            return cookie_file

    except Exception as e:
        logger.error(f"Playwright 获取 cookies 失败: {e}")
        return None
